version: '3.8'
services:
  php-apache-environment:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: redlock-web-2.0
    image: redlock-web-2.0:latest
    ports: 
      - 7077:80

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: redlock-db-vlc
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: kopinikmatnyamandilambung
        MYSQL_DATABASE: redlock-db
        MYSQL_USER: admin
        MYSQL_PASSWORD: kopinikmatnyamandilambung
    ports:
        - 3131:3306